### ISSUE TITLE
Matrix SVD Method

### ISSUE THREAD

**Issue by skyler-ruiter** [davidaustinm/MTH205-W20#5]
The `SVD()` Method of the matrix class uses the numpy linear algebra library to run `SVD` on `self.entries` returning the matrices `u`, `s`, and `vh`. The issue is that `vh` is already transposed when being returned by numpy so returning `vh.T` transposes again causing the three matrices multiplied together not resulting in `self` again. 

I'm not sure if this is intentional or not but seems like it should return the matrices in whatever form would allow them to multiply together to get self again instead of having the user transpose `vh` again

**Comment by davidaustinm** [comment]
Sorry, but I don't agree that this would be an improvement.  Different software packages handle this differently so a user will always need to investigate.  One thing that I don't like about numpy's choice is that it treats the left and right singular vectors differently.  If you want one set of singular vectors, you need the transpose but not for the other set of singular vectors.  In addition, you should expect to write A = U * Sigma * V.T, since that literally is the singular value decomposition.

**Comment by skyler-ruiter** [comment]
Thank you for the explanation Professor Austin, it was very helpful!
